---
debian:
  run: apt-get -y update && apt-get install -y git cmake gcc make python3 ruby ruby-dev python3-dev gengetopt doxygen
  from:
    - debian:stable
    - debian:unstable
    - debian:testing

fedora:
  run: dnf install -y git cmake gcc make ruby ruby-devel python3 python3-devel gengetopt doxygen
  from:
    - fedora:latest

opensuse:
  run: zypper install -y git cmake gcc make ruby ruby-devel python3 python3-devel gengetopt doxygen
  from:
    - opensuse:latest
