
/*
 * this file is part of pioe
 * 
 * Copyright (C) 2016-2017 Konrad Lother <k@hiddenbox.org>                            
 *                                                                               
 * This program is free software; you can redistribute it and/or                
 * modify it under the terms of the GNU General Public License                  
 * version 2, as published by the Free Software Foundation.                     
 *                                                                              
 * This program is distributed in the hope that it will be useful, but          
 * WITHOUT ANY WARRANTY; without even the implied warranty of                   
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU             
 * General Public License version 2 for more details.                           
 *                                                                              
 * You should have received a copy of the GNU General Public License            
 * version 2 along with this program; if not, write to the Free                 
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,          
 * MA 02110-1301, USA.     
 *
 */

#include "pioe/error.h"
#include "pioe/logger.h"
#include "pioe/thread.h"
//#include "pioe/plugin.h"
#include "pioe/util.h"
#include "pioe/engine.h"

/* this file is generated by cmake from cmdline.ggo.in */
#include "cmdline.h"

int main(int argc, char *argv[])
{
	if (argc <= 1) {
		fprintf(stderr, "See --help (or --detailed-help)\n");
		fflush(stderr);
		exit(EXIT_FAILURE);
	}

	struct cmdline_parser_params *params;
	struct gengetopt_args_info args_info;

	params = cmdline_parser_params_create();

	if (cmdline_parser(argc, argv, &args_info) != 0)
		exit(EXIT_FAILURE);

	params->initialize = 0;
	params->override = 1;

	if (args_info.config_given)
		if (cmdline_parser_config_file
		    (args_info.config_arg, &args_info, params)
		    != 0)
			exit(EXIT_FAILURE);

	if (args_info.log_file_given) {
		FILE *logfile = fopen(args_info.log_file_arg, "w+");
		if (NULL == logfile)
			PE_ABORT(pe_errno(), "Could not open logfile %s: %s",
				 args_info.log_file_arg,
				 pe_error_str(pe_errno()));
		pe_logger_init(logfile, logfile);
	} else {
		pe_logger_init(stdout, stdout);
	}

	if (args_info.log_format_given)
		pe_logger_set_format(args_info.log_format_arg);

	if (args_info.log_format_date_given)
		pe_logger_set_format_date(args_info.log_format_date_arg);

	if (args_info.log_format_time_given)
		pe_logger_set_format_time(args_info.log_format_time_arg);

	if (args_info.debug_flag)
		pe_logger_set_level(LALL);

	if (args_info.list_engines_given) {
		char *result[1024];
		int i;
		size_t len = pe_engine_find_engines(result);
		if (len == 0) {
			fprintf(stderr, "No engines found.\n");
			fflush(stderr);
			exit(EXIT_FAILURE);
		}

		for (i = 0; i < len; i++) {
			printf("%s\n", result[i]);
		}

		exit(EXIT_SUCCESS);

	}

	if (args_info.engine_given > 0) {
		int i;
		for (i = 0; i < args_info.engine_given; i++) {
			if (pe_engine_load_by_name(args_info.engine_arg[i]) !=
			    0) {
				LOG_ERROR("Could not load engine %s: %s",
					  args_info.engine_arg[i],
					  pe_error_str(pe_error_last()->code));
				continue;
			}

			LOG_INFO("Engine %s loaded.", args_info.engine_arg[i]);
		}
		if (pe_engine_init()) {
			PE_ABORT(-1, "error foo");
		}
	} else {
		fprintf(stderr,
			"No --engine given. See --help (or --detailed-help)\n");
		fflush(stderr);
		exit(EXIT_FAILURE);
	}

	if (args_info.script_given > 0) {
		int i;
		for (i = 0; i < args_info.inputs_num; i++) {
			LOG_DEBUG("Loading script %s", args_info.inputs[i]);
			if (pe_engine_load_script(args_info.inputs[i]) != 0) {
				LOG_ERROR("Could not load script %s: %s",
					  args_info.inputs[i],
					  pe_error_str(pe_error_last()->code));
				continue;
			}
		}
	} else {
		fprintf(stderr,
			"No --script given. See --help (or --detailed-help)\n");
		fflush(stderr);
		exit(EXIT_FAILURE);
	}

	LOG_DEBUG("Waiting for engine to finish all threads...");
	pe_engine_run();
	LOG_DEBUG("Engine finished all tasks.");

	return 0;
}
